### PR TITLE
Example notebook for spectral filtering feature 

### PR DESCRIPTION
**Pull request by JuliaKukulies**
Example notebook for [pull request on spectral filtering](https://github.com/climate-processes/tobac/commit/22547d0fb87d02431bfe1f74d33c2c2a348e1456). 

This tutorial shows how to use tobac with a spectral filter to track weather systems at specific spatial scales (in the example: meso-scale vortices with horizontal extents between 400 and 1000 km, based on simulated relative vorticity from a regional climate model). 

Note that the example file is not in the Zenodo repository yet, but ready to be uploaded.

### CODE REVIEW

**Comment by JuliaKukulies** [comment]
@fsenf, when submitting a new tutorial like this one: is the notebook file in ```tutorials/``` the only thing that needs to be submitted or do I need to do anything else (e.g. modifications in ```index.rst``` so that the new notebook will also be shown on the [readthedocs page](https://fsenf-tobac-tutorials.readthedocs.io/en/latest/)) ?

**Comment by fsenf** [comment]
@JuliaKukulies sorry for the delay answer. Any addition is welcome, so it could be either new notebooks or addition to `index.rst` or other documentation elements. For readthedocs, we still have a two step process in which PRs are first reviewed and merge here and second, I need to migrate them back to my personal fork https://github.com/fsenf/tobac-tutorials which actually hosts the webhook to RTD 

This will become easier soon with our own organization!

I will have a look at your notebook and rendering today (again sorry for super slow response time ...)

**Comment by fsenf** [comment]
@JuliaKukulies: The notebook looks super nice and renders well with sphinx. I cannot run by my own because I don't have your data around. Would you like to upload them to zenodo?

It is super hard to spot that the two first visualizations belong to the same field. What wonders me is that the value range get larger after filtering. Why should it be the case?

**Comment by JuliaKukulies** [comment]
No problem @fsenf and thanks for having a look at it! I am about to upload the data to zenodo now and will change the notebook so that the data can be downloaded. I will also make the figure more clear, maybe plot them next to each other and for the same value range. That was a good observation, I have mistakenly set the min and max values higher for the filtered output, but in fact the range of the values (if one would not set min and max), is smaller after the filtering as you would expect.

**Comment by fsenf** [comment]
@JuliaKukulies: Great! I have already added your notebook to index.rst locally. I will try to update your PR (still a tough task for me...)

**Comment by JuliaKukulies** [comment]
Perfect, many thanks for that @fsenf ! I have now uploaded the data to zenodo (with an indication that this belongs to tobac, as you suggested in the meeting) and included a data download section in the notebook. I also have changed the example figure a bit- note that actually chose a different case than in the first version of this example notebook, because I think it may be a bit more clear to show what the purpose and added value of the spectral filtering can be. Please have a look and let me know if it makes sense to you and if you can run the notebook without problems now.

**Comment by JuliaKukulies** [comment]
And it worked perfectly with your changes to `index.rst`, I could just pull over these

**Comment by fsenf** [comment]
@JuliaKukulies: All looks nice now! 

In my notebook session however the visualizations do not show up. I guess this has to do with the fact that `tobac` is changing the `matplotlib` backend to `agg`. Changing the order of imports seem to help. 

I will provide an updated version of the notebook after lunch break and start the merging and RTD rendering.

**Review by fsenf — APPROVED** [review]

**Pull request merged**
